### ISSUE TITLE
problem about unicode

### ISSUE THREAD

**Issue by caoguosong** [ThexXTURBOXx/Luyten#2]
Hi，

    I found a problem about unicode in 0.8.4.  When I opend a java class file with had chinese text, it showed:
![image](https://github.com/ThexXTURBOXx/Luyten/assets/67968014/b54b9423-96c5-44a9-ad68-dbb176e69383)
   
    When I chose "enable unicode replacement", it showed abnormal:
![image](https://github.com/ThexXTURBOXx/Luyten/assets/67968014/4db0f795-a896-48dc-8121-dede514c877e)

   The default font is : Consolas

   And when I selected the font: DialogInput,  it was corrected.

![image](https://github.com/ThexXTURBOXx/Luyten/assets/67968014/83d5f415-7179-4f9b-b5ec-16b8bb7e63f1)

   But there is no problem in 0.5.4 with default Consolas font.

   Can this problem will be fixed？ Or how to open the class file with the specified font?
   
   Thanks!

**Comment by ThexXTURBOXx** [comment]
Closing this in favor of https://github.com/bobbylight/RSyntaxTextArea/issues/530

**Comment by ThexXTURBOXx** [comment]
Luyten 0.8.6 fixes this entirely, btw! :)
